#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-only
"""Generate synthetic AVC ordering fixtures. Requires FFmpeg, ffprobe and x264."""
import json
from pathlib import Path
import re
import subprocess
import tempfile


def run(*args):
    return subprocess.run(args, check=True, capture_output=True)


def nals(data):
    return [n for n in re.split(b"\x00\x00\x00?\x01", data) if n]


def escape(data):
    result = bytearray()
    zeros = 0
    for byte in data:
        if zeros >= 2 and byte <= 3:
            result.append(3)
            zeros = 0
        result.append(byte)
        zeros = zeros + 1 if byte == 0 else 0
    return result


with tempfile.TemporaryDirectory() as directory:
    root = Path(directory)
    unrestricted = root / 'unrestricted.h264'
    qp = root / 'frames.qp'
    qp.write_text('0 I\n' + ''.join(f'{i} P\n' for i in range(1, 96)))
    source = subprocess.Popen([
        'ffmpeg', '-hide_banner', '-loglevel', 'error', '-f', 'lavfi', '-i',
        'color=c=red:s=2560x1440:r=30', '-frames:v', '96', '-f', 'yuv4mpegpipe', '-'
    ], stdout=subprocess.PIPE)
    encoded = subprocess.run([
        'x264', '--demuxer', 'y4m', '--preset', 'veryfast', '--bframes', '3',
        '--qpfile', str(qp), '--ref', '4', '--keyint', '96', '--aud', '--level', '5.1',
        '--output', str(unrestricted), '-'
    ], stdin=source.stdout, capture_output=True)
    source.stdout.close()
    assert source.wait() == 0
    encoded.check_returncode()
    trace = run('ffmpeg', '-hide_banner', '-i', str(unrestricted), '-c', 'copy',
                '-bsf:v', 'trace_headers', '-frames:v', '1', '-f', 'null', '-').stderr.decode()
    offset = int(re.search(r'] (\d+)\s+bitstream_restriction_flag', trace)[1])
    output = []
    for nal in nals(unrestricted.read_bytes()):
        if nal[0] & 31 == 7:
            # Widen the legal reorder allowance, as in an AirPlay POC type 0
            # SPS without bitstream restrictions. Coded pictures are unchanged.
            rbsp = nal.replace(b'\x00\x00\x03', b'\x00\x00')
            bits = ''.join(f'{byte:08b}' for byte in rbsp)[:offset] + '01'
            bits += '0' * (-len(bits) % 8)
            nal = escape(bytes(int(bits[i:i+8], 2) for i in range(0, len(bits), 8)))
        if nal[0] & 31 != 6:  # No encoder-version SEI metadata in fixtures.
            output.append(b'\x00\x00\x00\x01' + nal)
    unrestricted.write_bytes(b''.join(output))

    bframes = root / 'bframes.h264'
    run('ffmpeg', '-hide_banner', '-loglevel', 'error', '-f', 'lavfi', '-i',
        'color=c=red:s=640x360:r=60', '-frames:v', '96', '-c:v', 'libx264',
        '-preset', 'veryfast', '-x264-params',
        'aud=1:keyint=96:bframes=3:b-adapt=0:b-pyramid=none:ref=4', '-f', 'h264', str(bframes))
    bframes.write_bytes(b''.join(b'\x00\x00\x00\x01' + nal for nal in nals(bframes.read_bytes())
                                if nal[0] & 31 != 6))
    header = ['// SPDX-License-Identifier: GPL-3.0-only',
              '// Generated by generate_reorder_fixtures.py; synthetic red video only.',
              '#pragma once', '#include <cstdint>', 'namespace reorder_fixtures {']
    for name, path in [('unrestricted', unrestricted), ('bframes', bframes)]:
        run('ffmpeg', '-v', 'error', '-i', str(path), '-f', 'null', '-')
        frames = json.loads(run('ffprobe', '-v', 'error', '-show_entries',
                                'frame=pkt_pos,pict_type', '-of', 'json', str(path)).stdout)['frames']
        assert len(frames) == 96
        assert any(f['pict_type'] == 'B' for f in frames) == (name == 'bframes')
        presentation = {int(frame['pkt_pos']): i for i, frame in enumerate(frames)}
        data = path.read_bytes()
        offsets = [m.start() for m in re.finditer(b'\x00\x00\x00\x01\x09', data)] + [len(data)]
        assert len(offsets) == 97
        header.append(f'static constexpr uint8_t {name}_data[] = {{')
        header.extend('    ' + ','.join(f'0x{b:02x}' for b in data[i:i+20]) + ','
                      for i in range(0, len(data), 20))
        header.append('};')
        header.append(f'static constexpr uint32_t {name}_packets[][3] = {{')
        header.extend(f'    {{{a}, {b-a}, {presentation[a]}}},' for a, b in zip(offsets, offsets[1:]))
        header.append('};')
    header.append('} // namespace reorder_fixtures')
    Path(__file__).with_name('reorder_fixtures.h').write_text('\n'.join(header) + '\n')
