name: flutter_airplay
description: "Open-source AirPlay receiver with Flutter controls and native playback."
publish_to: none
version: 0.1.5+6

environment:
  sdk: ^3.13.2

dependencies:
  ffi: ^2.2.0
  archive: ^4.3.0
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  mixin_logger: ^0.2.0
  nativeapi: 0.4.0
  package_info_plus: ^10.2.2
  path: ^1.9.1
  path_provider: ^2.1.6
  share_plus: ^13.3.1
  shared_preferences: ^2.5.6
  json_annotation: ^4.12.0

dev_dependencies:
  ffigen: ^20.1.1
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  json_serializable: ^6.14.1
  build_runner: ^2.16.1

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/licenses/
    - lib/l10n/app_en.arb
    - lib/l10n/app_zh.arb
