# SPDX-License-Identifier: GPL-3.0-only
# Export the directories used by product targets. Preparation scans these roots
# for changes; source selection stays in CMake, including newly added files.
get_filename_component(airplay_root "${CMAKE_CURRENT_LIST_DIR}/../.." ABSOLUTE)
if(ANDROID)
    set(airplay_input_platform android)
elseif(WIN32)
    set(airplay_input_platform windows)
elseif(CMAKE_SYSTEM_NAME STREQUAL "iOS")
    set(airplay_input_platform ios)
elseif(APPLE)
    set(airplay_input_platform macos)
else()
    set(airplay_input_platform linux)
endif()
set(airplay_input_roots native/include native/cmake native/compat vendor)
foreach(target airplay_player receiver_core airplay_receiver_control airplay_ffi airplay_protocol)
    if(NOT TARGET ${target})
        continue()
    endif()
    get_target_property(sources ${target} SOURCES)
    get_target_property(source_dir ${target} SOURCE_DIR)
    foreach(source IN LISTS sources)
        if(source MATCHES "^\\$<")
            continue()
        endif()
        get_filename_component(source "${source}" ABSOLUTE BASE_DIR "${source_dir}")
        get_filename_component(directory "${source}" DIRECTORY)
        file(RELATIVE_PATH directory "${airplay_root}" "${directory}")
        if(NOT directory MATCHES "^\\.\\." AND NOT directory MATCHES "^build/")
            list(APPEND airplay_input_roots "${directory}")
        endif()
    endforeach()
endforeach()
if(ANDROID)
    list(APPEND airplay_input_roots native/backends/android/java)
endif()
list(REMOVE_DUPLICATES airplay_input_roots)
list(SORT airplay_input_roots)
string(REPLACE ";" "\n" airplay_input_text "${airplay_input_roots}")
file(MAKE_DIRECTORY "${airplay_root}/build/native-preparation")
file(WRITE "${airplay_root}/build/native-preparation/${airplay_input_platform}-sources.txt" "${airplay_input_text}\n")
