# SPDX-License-Identifier: GPL-3.0-only
set(core "${UXPLAY_SOURCE}/lib")
if(NOT TARGET plist)
    include(${CMAKE_CURRENT_LIST_DIR}/Plist.cmake)
endif()
add_library(llhttp STATIC ${core}/llhttp/api.c ${core}/llhttp/http.c ${core}/llhttp/llhttp.c)
target_include_directories(llhttp PUBLIC ${core}/llhttp)
add_library(playfair STATIC ${core}/playfair/hand_garble.c ${core}/playfair/modified_md5.c
    ${core}/playfair/omg_hax.c ${core}/playfair/playfair.c ${core}/playfair/sap_hash.c)
target_include_directories(playfair PUBLIC ${core}/playfair)
file(GLOB core_sources CONFIGURE_DEPENDS "${core}/*.c")
add_library(receiver_core STATIC ${core_sources})
if(ANDROID OR AIRPLAY_DNS_STUB)
    target_sources(receiver_core PRIVATE ${CMAKE_CURRENT_LIST_DIR}/../compat/dns_sd.c)
    target_include_directories(receiver_core PRIVATE ${CMAKE_CURRENT_LIST_DIR}/../compat)
endif()
target_include_directories(receiver_core PUBLIC ${core})
if(CRYPTO_PREFIX)
    target_include_directories(receiver_core PRIVATE ${CRYPTO_PREFIX}/include)
endif()
target_compile_definitions(receiver_core PRIVATE PLIST_210 PLIST_230 OPENSSL_API_COMPAT=0x10101000L)
if(CRYPTO_PREFIX)
    find_library(crypto_library NAMES crypto libcrypto PATHS ${CRYPTO_PREFIX}/lib ${CRYPTO_PREFIX}/lib64 NO_DEFAULT_PATH NO_CMAKE_FIND_ROOT_PATH REQUIRED)
else()
    find_package(OpenSSL REQUIRED)
    set(crypto_library OpenSSL::Crypto)
endif()
target_link_libraries(receiver_core PUBLIC plist llhttp playfair ${crypto_library})
