#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-only
"""Generate a synthetic HEVC stream with independently decodable GOPs."""
from pathlib import Path
import re
import subprocess
import tempfile


with tempfile.TemporaryDirectory() as directory:
    stream = Path(directory) / 'interruption.hevc'
    subprocess.run([
        'ffmpeg', '-nostdin', '-hide_banner', '-loglevel', 'error',
        '-f', 'lavfi', '-i',
        "nullsrc=size=160x96:rate=60,geq=lum='32+2*N':cb=128:cr=128",
        '-frames:v', '90', '-an', '-c:v', 'libx265', '-preset', 'ultrafast',
        '-pix_fmt', 'yuv420p', '-x265-params',
        'keyint=30:min-keyint=30:scenecut=0:bframes=0:open-gop=0:ref=1:aud=1:repeat-headers=1:pools=none:frame-threads=1:info=0:log-level=error',
        '-f', 'hevc', str(stream),
    ], check=True)
    # Remove SEI metadata while preserving parameter sets and coded pictures.
    nals = [nal for nal in re.split(b'\x00\x00\x00?\x01', stream.read_bytes())
            if nal and (nal[0] >> 1) & 63 not in (39, 40)]
    data = b''.join(b'\x00\x00\x00\x01' + nal for nal in nals)
    offsets = [match.start() for match in re.finditer(b'\x00\x00\x00\x01\x46\x01', data)] + [len(data)]
    assert len(offsets) == 91
    for index, (start, end) in enumerate(zip(offsets, offsets[1:])):
        types = [(nal[0] >> 1) & 63 for nal in re.split(b'\x00\x00\x00?\x01', data[start:end]) if nal]
        assert any(16 <= kind <= 23 for kind in types) == (index % 30 == 0)
    header = [
        '// SPDX-License-Identifier: GPL-3.0-only',
        '// Generated by generate_interruption_fixtures.py; synthetic luma ramp only.',
        '#pragma once', '#include <cstdint>', 'namespace interruption_fixtures {',
        'constexpr uint8_t data[] = {',
    ]
    header.extend('    ' + ','.join(f'0x{byte:02x}' for byte in data[i:i+20]) + ','
                  for i in range(0, len(data), 20))
    header.extend(['};', 'constexpr uint32_t packets[][2] = {'])
    header.extend(f'    {{{start}, {end-start}}},' for start, end in zip(offsets, offsets[1:]))
    header.extend(['};', '} // namespace interruption_fixtures'])
    Path(__file__).with_name('interruption_fixtures.h').write_text('\n'.join(header) + '\n')
